before_install:
  - sudo apt-get install -qq graphviz
before_script:
  - gem list
  - bundle show

rvm:
  - 2.3.1
gemfile:
  - gemfiles/Gemfile.rails-edge

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.x

    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-3.x

    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.0

    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-4.0

    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-5.0
