name: Test
on:
  push:
    branches:
      - develop
      - 1-2-stable
      - 2-0-stable
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7, 3.0, 3.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # Also installs gems
      - name: Install prerequisites for tests
        run: sudo apt-get install -y graphviz
      - name: Run tests
        run: bundle exec rake test

